name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: Rakambda/rakambda-github-workflows/.github/workflows/gradle-build.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}
      artifact-name: Gradle-Libs

  dropbox:
    uses: Rakambda/rakambda-github-workflows/.github/workflows/dropbox-publish-artifact.yml@main
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs:
      - build
    with:
      artifact-name: Gradle-Libs
      source: "filesecure-shaded.jar"
      target: "/Documents/JARs/FileSecure.jar"
    secrets:
      dropbox-token: ${{ secrets.DROPBOX_TOKEN }}
